### ISSUE TITLE
Transcoding not working

### ISSUE THREAD

**Issue by MeanLauraJean** [Helza/YouTubeTV.bundle#1]
A few days ago your latest version started not working. Transcoding fails.

**Comment by Helza** [comment]
idd, i can replicate the issue with that video, might be licensed music issue again but ill have to test and see if i can figure out what the problem is. Not sure when i can look into this :/

**Comment by Helza** [comment]
Update code, can you verify

**Comment by MeanLauraJean** [comment]
That resolved it - thanks so much! :)
